layout_spectrum: 0.9199785
typography_spectrum: 0.6299677
color:
  saturation: 0.4472246
  lightness: 0.3700322
  brandStrength: 0.6385607
  brandColors:
    - '#080A07'
    - '#006EDC'
    - '#C4A2A0'
    - '#886C68'
    - '#971841'
  rhythmicContrast: 0.7083781
name: A-cut-above
